-- ManzAllone v2 - Italian food catalog seed (CREA-INRAN derived values per 100g).
-- 235 items across 10 categories. Idempotent: ON CONFLICT (name) DO NOTHING.
-- Numbers are realistic averages, not lab-grade. Refine per item as needed.

insert into public.food_catalog
  (name, display_name, category, subcategory, avg_kcal_100g, avg_protein_100g, avg_carbs_100g, avg_fat_100g, avg_fiber_100g, default_portion_g, default_portion_unit, aliases, is_system)
values

-- ====================== PROTEINE ANIMALI ======================
('pollo_petto',                'Pollo petto',                'proteine_animali','carne_bianca', 110, 23.0,  0.0,  1.5, 0.0, 150, 'g', ARRAY['petto di pollo'], true),
('tacchino_petto',              'Tacchino petto',             'proteine_animali','carne_bianca', 107, 24.0,  0.0,  1.0, 0.0, 150, 'g', ARRAY['petto di tacchino'], true),
('manzo_magro',                 'Manzo magro',                'proteine_animali','carne_rossa',  116, 21.0,  0.0,  4.0, 0.0, 150, 'g', ARRAY['carne di manzo'], true),
('vitello',                     'Vitello',                    'proteine_animali','carne_rossa',   92, 20.0,  0.0,  1.0, 0.0, 150, 'g', ARRAY[]::text[], true),
('agnello',                     'Agnello',                    'proteine_animali','carne_rossa',  159, 20.0,  0.0,  9.0, 0.0, 150, 'g', ARRAY[]::text[], true),
('maiale_lonza',                'Maiale lonza',               'proteine_animali','carne_rossa',  118, 21.0,  0.0,  4.0, 0.0, 150, 'g', ARRAY['lonza di maiale'], true),
('coniglio',                    'Coniglio',                   'proteine_animali','carne_bianca', 102, 21.0,  0.0,  2.0, 0.0, 150, 'g', ARRAY[]::text[], true),
('uova_intere',                 'Uova intere',                'proteine_animali','uova',         128, 12.4,  1.0,  8.7, 0.0, 120, 'g', ARRAY['uovo','uova'], true),
('albumi',                      'Albumi',                     'proteine_animali','uova',          43, 11.0,  0.4,  0.0, 0.0, 100, 'g', ARRAY['albume'], true),
('pesce_bianco_orata',          'Orata',                      'proteine_animali','pesce',        121, 20.0,  0.0,  4.0, 0.0, 180, 'g', ARRAY[]::text[], true),
('branzino',                    'Branzino',                   'proteine_animali','pesce',         99, 21.0,  0.0,  2.0, 0.0, 180, 'g', ARRAY['spigola'], true),
('merluzzo',                    'Merluzzo',                   'proteine_animali','pesce',         71, 17.0,  0.0,  0.7, 0.0, 180, 'g', ARRAY[]::text[], true),
('nasello',                     'Nasello',                    'proteine_animali','pesce',         71, 17.0,  0.0,  0.7, 0.0, 180, 'g', ARRAY[]::text[], true),
('sogliola',                    'Sogliola',                   'proteine_animali','pesce',         83, 17.0,  0.8,  1.4, 0.0, 180, 'g', ARRAY[]::text[], true),
('salmone',                     'Salmone',                    'proteine_animali','pesce',        185, 20.0,  0.0, 12.0, 0.0, 150, 'g', ARRAY[]::text[], true),
('tonno_fresco',                'Tonno fresco',               'proteine_animali','pesce',        158, 22.0,  0.0,  7.0, 0.0, 150, 'g', ARRAY[]::text[], true),
('tonno_naturale_scatola',      'Tonno al naturale (scatola)','proteine_animali','pesce',        103, 25.0,  0.0,  0.6, 0.0,  80, 'g', ARRAY['tonno in scatola'], true),
('sgombro',                     'Sgombro',                    'proteine_animali','pesce',        170, 17.0,  0.0, 11.0, 0.0, 150, 'g', ARRAY['maccarello'], true),
('sardine',                     'Sardine',                    'proteine_animali','pesce',        129, 21.0,  0.0,  5.0, 0.0, 130, 'g', ARRAY[]::text[], true),
('alici',                       'Alici',                      'proteine_animali','pesce',         96, 17.0,  0.0,  3.0, 0.0, 130, 'g', ARRAY['acciughe'], true),
('gamberi',                     'Gamberi',                    'proteine_animali','crostacei',     71, 13.0,  1.5,  1.0, 0.0, 150, 'g', ARRAY['gamberetti'], true),
('calamari',                    'Calamari',                   'proteine_animali','molluschi',     68, 13.0,  0.7,  1.5, 0.0, 150, 'g', ARRAY['totani'], true),
('polpo',                       'Polpo',                      'proteine_animali','molluschi',     57, 11.0,  1.0,  1.0, 0.0, 180, 'g', ARRAY['polipo'], true),
('seppie',                      'Seppie',                     'proteine_animali','molluschi',     72, 14.0,  0.7,  1.5, 0.0, 180, 'g', ARRAY[]::text[], true),
('vongole',                     'Vongole',                    'proteine_animali','molluschi',     72, 10.0,  2.0,  2.5, 0.0, 150, 'g', ARRAY[]::text[], true),
('cozze',                       'Cozze',                      'proteine_animali','molluschi',     84, 12.0,  3.4,  2.7, 0.0, 250, 'g', ARRAY['mitili'], true),
('bresaola',                    'Bresaola',                   'proteine_animali','salumi',       151, 32.0,  0.0,  2.0, 0.0,  50, 'g', ARRAY[]::text[], true),
('prosciutto_crudo',            'Prosciutto crudo',           'proteine_animali','salumi',       159, 26.0,  0.5,  6.0, 0.0,  50, 'g', ARRAY[]::text[], true),
('prosciutto_cotto',            'Prosciutto cotto',           'proteine_animali','salumi',       132, 19.0,  0.5,  6.0, 0.0,  50, 'g', ARRAY[]::text[], true),
('tacchino_affettato',          'Tacchino affettato',         'proteine_animali','salumi',       110, 22.0,  1.0,  2.0, 0.0,  40, 'g', ARRAY['fesa di tacchino'], true),
('speck',                       'Speck',                      'proteine_animali','salumi',       303, 28.0,  0.5, 21.0, 0.0,  40, 'g', ARRAY[]::text[], true),

-- ====================== PROTEINE VEGETALI ======================
('tofu',                        'Tofu',                       'proteine_vegetali','legumi',        76,  8.0,  1.9,  4.8, 0.3, 120, 'g', ARRAY[]::text[], true),
('tempeh',                      'Tempeh',                     'proteine_vegetali','legumi',       192, 19.0,  9.0, 11.0, 1.4, 100, 'g', ARRAY[]::text[], true),
('seitan',                      'Seitan',                     'proteine_vegetali','glutine',      145, 25.0, 14.0,  2.0, 0.6, 100, 'g', ARRAY[]::text[], true),
('ceci_cotti',                  'Ceci cotti',                 'proteine_vegetali','legumi',       119,  7.0, 17.0,  2.4, 5.4, 150, 'g', ARRAY['ceci'], true),
('lenticchie_rosse_cotte',      'Lenticchie rosse cotte',     'proteine_vegetali','legumi',       116,  9.0, 20.0,  0.4, 8.0, 150, 'g', ARRAY['lenticchie rosse'], true),
('lenticchie_verdi',            'Lenticchie verdi cotte',     'proteine_vegetali','legumi',       116,  9.0, 20.0,  0.4, 8.0, 150, 'g', ARRAY['lenticchie'], true),
('fagioli_borlotti_cotti',      'Fagioli borlotti cotti',     'proteine_vegetali','legumi',       124,  9.0, 17.0,  0.7, 6.4, 150, 'g', ARRAY['borlotti'], true),
('fagioli_cannellini',          'Fagioli cannellini cotti',   'proteine_vegetali','legumi',       137,  9.0, 22.0,  1.0, 7.0, 150, 'g', ARRAY['cannellini'], true),
('fagioli_neri',                'Fagioli neri cotti',         'proteine_vegetali','legumi',       132,  9.0, 24.0,  0.5, 8.7, 150, 'g', ARRAY[]::text[], true),
('piselli_cotti',               'Piselli cotti',              'proteine_vegetali','legumi',        84,  5.0, 13.0,  0.6, 5.0, 150, 'g', ARRAY['piselli'], true),
('soia_edamame',                'Edamame',                    'proteine_vegetali','legumi',       122, 11.0,  9.0,  5.0, 5.0, 100, 'g', ARRAY['edamame','soia'], true),
('hummus',                      'Hummus',                     'proteine_vegetali','spalmabili',   166,  8.0, 14.0, 10.0, 6.0,  60, 'g', ARRAY[]::text[], true),

-- ====================== CARBOIDRATI ======================
('pasta_semola_secca',          'Pasta di semola (secca)',    'carboidrati','pasta',              353, 11.0, 73.0,  1.5, 2.7,  80, 'g', ARRAY['pasta'], true),
('pasta_integrale_secca',       'Pasta integrale (secca)',    'carboidrati','pasta',              348, 13.0, 64.0,  2.0, 8.0,  80, 'g', ARRAY['pasta integrale'], true),
('riso_bianco_crudo',           'Riso bianco (crudo)',        'carboidrati','riso',               332,  7.0, 80.0,  0.4, 0.5,  70, 'g', ARRAY['riso'], true),
('riso_integrale_crudo',        'Riso integrale (crudo)',     'carboidrati','riso',               357,  7.5, 77.0,  1.9, 1.9,  70, 'g', ARRAY[]::text[], true),
('riso_basmati_crudo',          'Riso basmati (crudo)',       'carboidrati','riso',               350,  7.5, 78.0,  1.0, 0.4,  70, 'g', ARRAY[]::text[], true),
('riso_venere_crudo',           'Riso Venere (crudo)',        'carboidrati','riso',               351,  8.0, 77.0,  2.0, 2.0,  70, 'g', ARRAY[]::text[], true),
('quinoa_cruda',                'Quinoa (cruda)',             'carboidrati','cereali',            368, 14.0, 64.0,  6.0, 7.0,  70, 'g', ARRAY['quinoa'], true),
('farro_perlato_crudo',         'Farro perlato (crudo)',      'carboidrati','cereali',            335, 15.0, 67.0,  2.5, 7.0,  70, 'g', ARRAY['farro'], true),
('orzo_perlato_crudo',          'Orzo perlato (crudo)',       'carboidrati','cereali',            319, 10.5, 71.0,  1.4, 9.2,  70, 'g', ARRAY['orzo'], true),
('grano_saraceno',              'Grano saraceno',             'carboidrati','cereali',            343, 13.0, 71.0,  3.4,10.0,  70, 'g', ARRAY[]::text[], true),
('bulgur_crudo',                'Bulgur (crudo)',             'carboidrati','cereali',            342, 12.0, 76.0,  1.3,12.5,  70, 'g', ARRAY['bulgur'], true),
('cous_cous_crudo',             'Cous cous (crudo)',          'carboidrati','cereali',            376, 12.8, 77.0,  0.6, 5.0,  70, 'g', ARRAY['couscous'], true),
('avena_in_chicchi',            'Avena in chicchi',           'carboidrati','cereali',            379, 13.0, 67.0,  6.5,10.0,  60, 'g', ARRAY[]::text[], true),
('fiocchi_avena',               'Fiocchi d''avena',           'carboidrati','cereali',            389, 13.0, 66.0,  7.0,10.0,  50, 'g', ARRAY['avena','oats'], true),
('polenta',                     'Polenta',                    'carboidrati','cereali',            358,  8.7, 78.0,  1.5, 5.0,  70, 'g', ARRAY[]::text[], true),
('pane_bianco',                 'Pane bianco',                'carboidrati','pane',               265,  8.4, 50.0,  3.3, 2.4,  60, 'g', ARRAY['pane'], true),
('pane_integrale',              'Pane integrale',             'carboidrati','pane',               247,  8.5, 41.0,  3.5, 7.0,  60, 'g', ARRAY[]::text[], true),
('pane_segale',                 'Pane di segale',             'carboidrati','pane',               259,  8.5, 48.0,  1.7, 6.0,  60, 'g', ARRAY[]::text[], true),
('pane_kamut',                  'Pane kamut',                 'carboidrati','pane',               247,  8.0, 50.0,  1.5, 6.0,  60, 'g', ARRAY[]::text[], true),
('pane_azzimo',                 'Pane azzimo',                'carboidrati','pane',               350, 11.0, 70.0,  4.0, 3.0,  40, 'g', ARRAY[]::text[], true),
('piadina',                     'Piadina',                    'carboidrati','pane',               290,  8.0, 47.0,  8.0, 2.0,  80, 'g', ARRAY[]::text[], true),
('tortilla_grano',              'Tortilla di grano',          'carboidrati','pane',               305,  8.0, 50.0,  7.0, 3.0,  70, 'g', ARRAY['tortilla'], true),
('fette_biscottate',            'Fette biscottate',           'carboidrati','cereali_secchi',     408, 12.0, 78.0,  6.0, 3.0,  20, 'g', ARRAY[]::text[], true),
('fette_biscottate_integrali',  'Fette biscottate integrali', 'carboidrati','cereali_secchi',     380, 11.0, 67.0,  7.0, 8.0,  20, 'g', ARRAY[]::text[], true),
('crackers',                    'Crackers',                   'carboidrati','cereali_secchi',     425, 11.0, 70.0, 11.0, 3.0,  25, 'g', ARRAY[]::text[], true),
('grissini',                    'Grissini',                   'carboidrati','cereali_secchi',     433, 13.0, 70.0, 13.0, 3.0,  15, 'g', ARRAY[]::text[], true),
('gallette_riso',               'Gallette di riso',           'carboidrati','cereali_secchi',     376,  7.0, 81.0,  2.0, 1.0,  10, 'g', ARRAY[]::text[], true),
('gallette_mais',               'Gallette di mais',           'carboidrati','cereali_secchi',     386,  7.0, 82.0,  2.5, 4.0,  10, 'g', ARRAY[]::text[], true),
('patate_lesse',                'Patate lesse',               'carboidrati','tuberi',              80,  1.8, 18.0,  0.1, 1.8, 250, 'g', ARRAY['patate'], true),
('patate_dolci',                'Patate dolci',               'carboidrati','tuberi',              86,  1.6, 20.0,  0.1, 3.0, 200, 'g', ARRAY['sweet potato'], true),

-- ====================== VERDURE ======================
('spinaci_freschi',             'Spinaci',                    'verdure','foglia',                  23,  2.9,  1.7,  0.4, 1.9, 200, 'g', ARRAY['spinaci'], true),
('insalata_mista',              'Insalata mista',             'verdure','foglia',                  16,  1.5,  1.6,  0.2, 1.5, 100, 'g', ARRAY[]::text[], true),
('lattuga',                     'Lattuga',                    'verdure','foglia',                  19,  1.8,  2.2,  0.4, 1.5, 100, 'g', ARRAY[]::text[], true),
('rucola',                      'Rucola',                     'verdure','foglia',                  28,  2.6,  3.7,  0.7, 1.6,  50, 'g', ARRAY[]::text[], true),
('valeriana',                   'Valeriana',                  'verdure','foglia',                  21,  2.0,  3.5,  0.4, 1.5,  50, 'g', ARRAY[]::text[], true),
('radicchio',                   'Radicchio',                  'verdure','foglia',                  13,  1.4,  1.8,  0.2, 3.0, 100, 'g', ARRAY[]::text[], true),
('cicoria',                     'Cicoria',                    'verdure','foglia',                  23,  1.4,  0.7,  0.4, 3.0, 200, 'g', ARRAY[]::text[], true),
('scarola',                     'Scarola',                    'verdure','foglia',                  17,  1.3,  0.7,  0.3, 3.0, 200, 'g', ARRAY[]::text[], true),
('pomodori_freschi',            'Pomodori',                   'verdure','frutto',                  19,  1.0,  3.5,  0.2, 1.0, 200, 'g', ARRAY['pomodoro'], true),
('pomodorini_ciliegino',        'Pomodorini ciliegino',       'verdure','frutto',                  18,  1.0,  3.5,  0.2, 1.0, 150, 'g', ARRAY['pomodorini'], true),
('cetrioli',                    'Cetrioli',                   'verdure','frutto',                  14,  0.7,  1.8,  0.2, 0.8, 150, 'g', ARRAY['cetriolo'], true),
('peperoni_rossi',              'Peperoni rossi',             'verdure','frutto',                  31,  1.0,  6.4,  0.3, 2.0, 150, 'g', ARRAY['peperone'], true),
('peperoni_gialli',             'Peperoni gialli',            'verdure','frutto',                  27,  1.0,  6.0,  0.3, 1.5, 150, 'g', ARRAY[]::text[], true),
('zucchine',                    'Zucchine',                   'verdure','frutto',                  11,  1.3,  1.4,  0.1, 1.2, 200, 'g', ARRAY['zucchina'], true),
('melanzane',                   'Melanzane',                  'verdure','frutto',                  18,  1.1,  2.6,  0.1, 2.6, 200, 'g', ARRAY['melanzana'], true),
('carote',                      'Carote',                     'verdure','radice',                  35,  1.1,  7.6,  0.2, 3.1, 150, 'g', ARRAY['carota'], true),
('sedano',                      'Sedano',                     'verdure','fusto',                   20,  0.7,  2.4,  0.2, 1.6, 100, 'g', ARRAY[]::text[], true),
('finocchi',                    'Finocchi',                   'verdure','bulbo',                    9,  1.2,  1.0,  0.2, 2.2, 200, 'g', ARRAY['finocchio'], true),
('broccoli',                    'Broccoli',                   'verdure','crucifere',               27,  3.0,  2.2,  0.3, 3.1, 200, 'g', ARRAY['broccolo'], true),
('cavolfiori',                  'Cavolfiori',                 'verdure','crucifere',               25,  3.2,  2.7,  0.2, 2.4, 200, 'g', ARRAY['cavolfiore'], true),
('cavolo_verza',                'Cavolo verza',               'verdure','crucifere',               24,  2.1,  2.3,  0.2, 3.4, 200, 'g', ARRAY['verza'], true),
('cavolini_bruxelles',          'Cavolini di Bruxelles',      'verdure','crucifere',               37,  4.2,  4.3,  0.5, 5.0, 200, 'g', ARRAY[]::text[], true),
('asparagi',                    'Asparagi',                   'verdure','fusto',                   24,  3.6,  3.3,  0.2, 2.0, 200, 'g', ARRAY[]::text[], true),
('carciofi',                    'Carciofi',                   'verdure','fiore',                   22,  2.7,  2.5,  0.2, 5.5, 150, 'g', ARRAY['carciofo'], true),
('fagiolini',                   'Fagiolini',                  'verdure','baccello',                18,  2.1,  2.4,  0.1, 2.9, 200, 'g', ARRAY[]::text[], true),
('zucca',                       'Zucca',                      'verdure','frutto',                  18,  1.1,  3.5,  0.1, 1.0, 200, 'g', ARRAY['zucca gialla'], true),
('funghi_champignon',           'Funghi champignon',          'verdure','funghi',                  26,  3.9,  0.7,  0.2, 2.5, 150, 'g', ARRAY['champignon','prataioli'], true),
('funghi_porcini',              'Funghi porcini',             'verdure','funghi',                  26,  3.7,  1.0,  0.7, 2.5, 150, 'g', ARRAY['porcini'], true),
('cipolle',                     'Cipolle',                    'verdure','bulbo',                   26,  1.0,  5.7,  0.1, 1.0, 100, 'g', ARRAY['cipolla'], true),
('aglio',                       'Aglio',                      'verdure','bulbo',                   41,  0.9,  8.4,  0.6, 3.1,   5, 'g', ARRAY[]::text[], true),
('scalogno',                    'Scalogno',                   'verdure','bulbo',                   72,  2.5, 16.0,  0.1, 3.2,  50, 'g', ARRAY[]::text[], true),
('porro',                       'Porro',                      'verdure','bulbo',                   29,  2.1,  5.2,  0.1, 2.9, 150, 'g', ARRAY['porri'], true),
('ravanelli',                   'Ravanelli',                  'verdure','radice',                  13,  0.8,  1.8,  0.1, 1.3, 100, 'g', ARRAY['rapanelli'], true),
('barbabietole',                'Barbabietole',               'verdure','radice',                  19,  1.1,  4.0,  0.0, 2.6, 100, 'g', ARRAY['barbabietola','rape rosse'], true),

-- ====================== FRUTTA ======================
('mele',                        'Mele',                       'frutta','pomacee',                  53,  0.3, 13.7,  0.1, 2.0, 200, 'g', ARRAY['mela'], true),
('pere',                        'Pere',                       'frutta','pomacee',                  35,  0.3,  8.8,  0.1, 3.8, 200, 'g', ARRAY['pera'], true),
('banane',                      'Banane',                     'frutta','tropicale',                65,  1.2, 15.4,  0.3, 1.8, 120, 'g', ARRAY['banana'], true),
('arance',                      'Arance',                     'frutta','agrumi',                   34,  0.7,  7.8,  0.2, 1.6, 200, 'g', ARRAY['arancia'], true),
('mandarini',                   'Mandarini',                  'frutta','agrumi',                   53,  0.9, 17.6,  0.3, 1.7, 150, 'g', ARRAY['mandarino'], true),
('clementine',                  'Clementine',                 'frutta','agrumi',                   47,  0.9,  9.0,  0.2, 1.7, 150, 'g', ARRAY['clementina'], true),
('pompelmo',                    'Pompelmo',                   'frutta','agrumi',                   26,  0.6,  6.2,  0.0, 1.6, 300, 'g', ARRAY[]::text[], true),
('kiwi',                        'Kiwi',                       'frutta','tropicale',                44,  1.2,  9.0,  0.6, 2.6, 150, 'g', ARRAY[]::text[], true),
('fragole',                     'Fragole',                    'frutta','frutti_di_bosco',          30,  0.7,  5.4,  0.4, 1.5, 150, 'g', ARRAY['fragola'], true),
('mirtilli',                    'Mirtilli',                   'frutta','frutti_di_bosco',          38,  0.9,  5.1,  0.2, 3.1, 100, 'g', ARRAY['mirtillo'], true),
('lamponi',                     'Lamponi',                    'frutta','frutti_di_bosco',          35,  1.0,  6.5,  0.6, 7.0, 100, 'g', ARRAY['lampone'], true),
('more',                        'More',                       'frutta','frutti_di_bosco',          37,  1.4,  5.4,  0.6, 3.2, 100, 'g', ARRAY['mora'], true),
('ciliegie',                    'Ciliegie',                   'frutta','drupacee',                 38,  0.8,  9.0,  0.1, 1.3, 150, 'g', ARRAY['ciliegia'], true),
('pesche',                      'Pesche',                     'frutta','drupacee',                 28,  0.8,  6.1,  0.1, 1.6, 200, 'g', ARRAY['pesca'], true),
('albicocche',                  'Albicocche',                 'frutta','drupacee',                 28,  0.4,  6.8,  0.1, 1.5, 150, 'g', ARRAY['albicocca'], true),
('prugne',                      'Prugne',                     'frutta','drupacee',                 42,  0.5, 10.5,  0.1, 1.5, 150, 'g', ARRAY['prugna','susine'], true),
('uva',                         'Uva',                        'frutta','altri',                    61,  0.5, 15.6,  0.1, 1.5, 150, 'g', ARRAY[]::text[], true),
('anguria',                     'Anguria',                    'frutta','tropicale',                16,  0.4,  3.7,  0.0, 0.2, 300, 'g', ARRAY['cocomero'], true),
('melone',                      'Melone',                     'frutta','tropicale',                33,  0.8,  7.4,  0.2, 0.7, 200, 'g', ARRAY[]::text[], true),
('ananas',                      'Ananas',                     'frutta','tropicale',                40,  0.5, 10.0,  0.1, 1.0, 200, 'g', ARRAY[]::text[], true),
('mango',                       'Mango',                      'frutta','tropicale',                53,  0.5, 12.6,  0.2, 1.6, 150, 'g', ARRAY[]::text[], true),
('papaya',                      'Papaya',                     'frutta','tropicale',                28,  0.4,  6.9,  0.1, 2.3, 200, 'g', ARRAY[]::text[], true),
('avocado',                     'Avocado',                    'frutta','tropicale',               231,  4.4,  1.8, 23.0, 3.3, 100, 'g', ARRAY[]::text[], true),
('fichi',                       'Fichi',                      'frutta','altri',                    47,  0.9, 11.2,  0.2, 2.0, 150, 'g', ARRAY['fico'], true),
('datteri',                     'Datteri',                    'frutta','essiccata',               256,  2.4, 63.1,  0.6, 6.7,  30, 'g', ARRAY['dattero'], true),
('prugne_secche',               'Prugne secche',              'frutta','essiccata',               220,  2.2, 55.0,  0.4, 8.4,  30, 'g', ARRAY['prugne essiccate'], true),
('uva_passa',                   'Uva passa',                  'frutta','essiccata',               283,  1.9, 72.0,  0.6, 3.1,  30, 'g', ARRAY['uvetta','sultanina'], true),

-- ====================== LATTICINI ======================
('latte_intero',                'Latte intero',               'latticini','latte',                  64,  3.3,  4.9,  3.6, 0.0, 250, 'ml', ARRAY[]::text[], true),
('latte_parzialmente_scremato', 'Latte parz. scremato',       'latticini','latte',                  46,  3.4,  5.0,  1.7, 0.0, 250, 'ml', ARRAY['latte ps'], true),
('latte_scremato',              'Latte scremato',             'latticini','latte',                  36,  3.6,  5.1,  0.2, 0.0, 250, 'ml', ARRAY[]::text[], true),
('latte_senza_lattosio',        'Latte senza lattosio',       'latticini','latte',                  46,  3.4,  5.0,  1.7, 0.0, 250, 'ml', ARRAY[]::text[], true),
('yogurt_intero',               'Yogurt intero',              'latticini','yogurt',                 65,  3.8,  4.3,  3.9, 0.0, 150, 'g', ARRAY[]::text[], true),
('yogurt_magro',                'Yogurt magro',               'latticini','yogurt',                 36,  3.3,  4.0,  0.1, 0.0, 150, 'g', ARRAY[]::text[], true),
('yogurt_greco_intero',         'Yogurt greco intero',        'latticini','yogurt',                116,  6.3,  3.9,  9.0, 0.0, 150, 'g', ARRAY[]::text[], true),
('yogurt_greco_zero',           'Yogurt greco 0%',            'latticini','yogurt',                 57, 10.0,  3.5,  0.2, 0.0, 150, 'g', ARRAY['yogurt greco magro'], true),
('skyr',                        'Skyr',                       'latticini','yogurt',                 56, 11.0,  3.5,  0.2, 0.0, 150, 'g', ARRAY[]::text[], true),
('kefir',                       'Kefir',                      'latticini','yogurt',                 60,  3.4,  4.7,  3.0, 0.0, 200, 'ml', ARRAY[]::text[], true),
('ricotta_vaccina',             'Ricotta vaccina',            'latticini','formaggi_freschi',      146,  8.8,  3.5, 10.9, 0.0, 100, 'g', ARRAY['ricotta'], true),
('fiocchi_latte',               'Fiocchi di latte',           'latticini','formaggi_freschi',       95, 12.0,  3.4,  4.0, 0.0, 100, 'g', ARRAY['cottage cheese'], true),
('mozzarella_vaccina',          'Mozzarella vaccina',         'latticini','formaggi_freschi',      253, 18.7,  0.7, 19.5, 0.0, 100, 'g', ARRAY['mozzarella'], true),
('mozzarella_bufala',           'Mozzarella di bufala',       'latticini','formaggi_freschi',      288, 17.0,  0.4, 24.0, 0.0, 100, 'g', ARRAY[]::text[], true),
('burrata',                     'Burrata',                    'latticini','formaggi_freschi',      330, 17.0,  1.0, 28.0, 0.0,  80, 'g', ARRAY[]::text[], true),
('philadelphia_classico',       'Philadelphia classico',      'latticini','spalmabili',            257,  5.5,  4.1, 24.7, 0.0,  30, 'g', ARRAY['philadelphia'], true),
('philadelphia_light',          'Philadelphia light',         'latticini','spalmabili',            162,  8.0,  5.0, 12.0, 0.0,  30, 'g', ARRAY[]::text[], true),
('robiola',                     'Robiola',                    'latticini','formaggi_molli',        254, 16.0,  1.0, 21.0, 0.0,  50, 'g', ARRAY[]::text[], true),
('primo_sale',                  'Primo sale',                 'latticini','formaggi_freschi',      261, 17.0,  0.5, 21.0, 0.0,  50, 'g', ARRAY[]::text[], true),
('feta',                        'Feta',                       'latticini','formaggi_freschi',      250, 14.0,  4.0, 21.0, 0.0,  40, 'g', ARRAY[]::text[], true),
('parmigiano',                  'Parmigiano Reggiano',        'latticini','formaggi_stagionati',   392, 33.0,  0.0, 28.4, 0.0,  15, 'g', ARRAY['parmigiano reggiano','parmigiano grattugiato'], true),
('grana_padano',                'Grana Padano',               'latticini','formaggi_stagionati',   384, 33.0,  0.0, 28.0, 0.0,  15, 'g', ARRAY['grana'], true),
('pecorino',                    'Pecorino',                   'latticini','formaggi_stagionati',   387, 26.0,  0.0, 31.0, 0.0,  15, 'g', ARRAY[]::text[], true),
('gorgonzola',                  'Gorgonzola',                 'latticini','formaggi_erborinati',   330, 19.0,  0.7, 28.0, 0.0,  30, 'g', ARRAY[]::text[], true),
('taleggio',                    'Taleggio',                   'latticini','formaggi_molli',        315, 19.0,  0.6, 26.0, 0.0,  30, 'g', ARRAY[]::text[], true),
('brie',                        'Brie',                       'latticini','formaggi_molli',        334, 21.0,  0.5, 28.0, 0.0,  30, 'g', ARRAY[]::text[], true),
('camembert',                   'Camembert',                  'latticini','formaggi_molli',        300, 20.0,  0.5, 24.0, 0.0,  30, 'g', ARRAY[]::text[], true),

-- ====================== GRASSI BUONI ======================
('olio_evo',                    'Olio EVO',                   'grassi_buoni','oli',                884,  0.0,  0.0,100.0, 0.0,  10, 'ml', ARRAY['olio extravergine','olio d''oliva','olio extravergine di oliva'], true),
('olio_semi_lino',              'Olio di semi di lino',       'grassi_buoni','oli',                884,  0.0,  0.0,100.0, 0.0,   5, 'ml', ARRAY[]::text[], true),
('olio_cocco',                  'Olio di cocco',              'grassi_buoni','oli',                862,  0.0,  0.0, 99.1, 0.0,  10, 'ml', ARRAY[]::text[], true),
('burro',                       'Burro',                      'grassi_buoni','grassi_animali',     717,  0.8,  0.7, 81.0, 0.0,  10, 'g',  ARRAY[]::text[], true),
('ghee',                        'Ghee',                       'grassi_buoni','grassi_animali',     900,  0.3,  0.0, 99.5, 0.0,  10, 'g',  ARRAY[]::text[], true),
('olive_verdi',                 'Olive verdi',                'grassi_buoni','olive',              142,  1.0,  1.0, 15.0, 4.0,  30, 'g',  ARRAY[]::text[], true),
('olive_nere',                  'Olive nere',                 'grassi_buoni','olive',              235,  1.6,  1.0, 24.0, 3.3,  30, 'g',  ARRAY[]::text[], true),
('mandorle',                    'Mandorle',                   'grassi_buoni','frutta_secca',       603, 22.0,  5.0, 51.0,12.7,  30, 'g',  ARRAY[]::text[], true),
('noci',                        'Noci',                       'grassi_buoni','frutta_secca',       689, 14.0,  5.0, 64.0, 5.0,  30, 'g',  ARRAY[]::text[], true),
('nocciole',                    'Nocciole',                   'grassi_buoni','frutta_secca',       655, 14.0,  6.0, 64.0, 8.0,  30, 'g',  ARRAY[]::text[], true),
('anacardi',                    'Anacardi',                   'grassi_buoni','frutta_secca',       598, 18.0, 30.0, 46.0, 3.0,  30, 'g',  ARRAY[]::text[], true),
('pistacchi',                   'Pistacchi',                  'grassi_buoni','frutta_secca',       608, 19.0, 16.0, 51.0,10.0,  30, 'g',  ARRAY[]::text[], true),
('semi_chia',                   'Semi di chia',               'grassi_buoni','semi',               486, 17.0, 42.0, 31.0,34.0,  15, 'g',  ARRAY[]::text[], true),
('semi_lino',                   'Semi di lino',               'grassi_buoni','semi',               534, 18.0, 29.0, 42.0,27.0,  15, 'g',  ARRAY[]::text[], true),
('semi_girasole',               'Semi di girasole',           'grassi_buoni','semi',               599, 21.0, 20.0, 52.0, 8.6,  15, 'g',  ARRAY[]::text[], true),
('semi_zucca',                  'Semi di zucca',              'grassi_buoni','semi',               559, 30.0, 11.0, 49.0, 6.0,  15, 'g',  ARRAY[]::text[], true),
('semi_sesamo',                 'Semi di sesamo',             'grassi_buoni','semi',               596, 18.0, 13.0, 52.0,12.0,  15, 'g',  ARRAY[]::text[], true),
('tahina',                      'Tahina',                     'grassi_buoni','creme',              595, 19.0, 21.0, 53.0, 9.0,  15, 'g',  ARRAY['tahini'], true),
('burro_arachidi',              'Burro di arachidi',          'grassi_buoni','creme',              588, 25.0, 20.0, 50.0, 6.0,  15, 'g',  ARRAY['peanut butter'], true),
('burro_mandorle',              'Burro di mandorle',          'grassi_buoni','creme',              614, 21.0, 19.0, 56.0,10.0,  15, 'g',  ARRAY[]::text[], true),

-- ====================== SNACK DOLCI ======================
('cioccolato_fondente_70',      'Cioccolato fondente 70%',    'snack_dolci','cioccolato',          587,  9.0, 30.0, 43.0,12.0,  25, 'g', ARRAY['cioccolato fondente'], true),
('cioccolato_fondente_85',      'Cioccolato fondente 85%',    'snack_dolci','cioccolato',          605, 12.0, 14.0, 50.0,11.0,  20, 'g', ARRAY[]::text[], true),
('cioccolato_latte',            'Cioccolato al latte',        'snack_dolci','cioccolato',          545,  7.5, 56.0, 32.0, 1.0,  25, 'g', ARRAY[]::text[], true),
('biscotti_secchi',             'Biscotti secchi',            'snack_dolci','biscotti',            442,  7.0, 73.0, 13.0, 2.5,  30, 'g', ARRAY[]::text[], true),
('pavesini',                    'Pavesini',                   'snack_dolci','biscotti',            408,  9.0, 75.0,  8.0, 1.0,  15, 'g', ARRAY[]::text[], true),
('gocciole',                    'Gocciole',                   'snack_dolci','biscotti',            504,  6.0, 67.0, 23.0, 2.5,  30, 'g', ARRAY[]::text[], true),
('plumcake',                    'Plumcake',                   'snack_dolci','dolci_pronti',        415,  6.0, 55.0, 19.0, 1.5,  40, 'g', ARRAY[]::text[], true),
('brioche',                     'Brioche',                    'snack_dolci','pasticceria',         360,  8.0, 50.0, 14.0, 2.0,  60, 'g', ARRAY[]::text[], true),
('cornetto_vuoto',              'Cornetto vuoto',             'snack_dolci','pasticceria',         391,  7.0, 49.0, 19.0, 2.0,  60, 'g', ARRAY['croissant vuoto'], true),
('cornetto_marmellata',         'Cornetto alla marmellata',   'snack_dolci','pasticceria',         367,  6.0, 53.0, 14.0, 2.0,  70, 'g', ARRAY[]::text[], true),
('cornetto_cioccolato',         'Cornetto al cioccolato',     'snack_dolci','pasticceria',         412,  7.0, 49.0, 21.0, 2.5,  70, 'g', ARRAY[]::text[], true),
('ciambellone',                 'Ciambellone',                'snack_dolci','pasticceria',         380,  7.0, 56.0, 14.0, 1.5,  60, 'g', ARRAY[]::text[], true),
('crostata',                    'Crostata',                   'snack_dolci','pasticceria',         380,  5.0, 60.0, 13.0, 1.0,  80, 'g', ARRAY[]::text[], true),
('marmellata',                  'Marmellata',                 'snack_dolci','spalmabili',          250,  0.5, 60.0,  0.1, 1.0,  20, 'g', ARRAY['confettura'], true),
('miele',                       'Miele',                      'snack_dolci','dolcificanti',        304,  0.3, 82.0,  0.0, 0.0,  15, 'g', ARRAY[]::text[], true),
('nutella',                     'Nutella',                    'snack_dolci','spalmabili',          539,  6.0, 57.0, 30.0, 4.0,  15, 'g', ARRAY['crema spalmabile cacao'], true),
('zucchero_bianco',             'Zucchero bianco',            'snack_dolci','dolcificanti',        392,  0.0,100.0,  0.0, 0.0,   5, 'g', ARRAY['zucchero'], true),
('dolcificante_eritritolo',     'Eritritolo',                 'snack_dolci','dolcificanti',          0,  0.0,100.0,  0.0, 0.0,   5, 'g', ARRAY['eritritolo'], true),
('dolcificante_stevia',         'Stevia',                     'snack_dolci','dolcificanti',          0,  0.0,  0.0,  0.0, 0.0,   1, 'g', ARRAY['stevia'], true),

-- ====================== BEVANDE NON ALCOLICHE ======================
('acqua_naturale',              'Acqua naturale',             'bevande_nonalcoliche','acqua',        0,  0.0,  0.0,  0.0, 0.0, 500, 'ml', ARRAY['acqua'], true),
('acqua_frizzante',             'Acqua frizzante',            'bevande_nonalcoliche','acqua',        0,  0.0,  0.0,  0.0, 0.0, 500, 'ml', ARRAY[]::text[], true),
('caffe_espresso',              'Caffè espresso',             'bevande_nonalcoliche','caffe',        2,  0.1,  0.3,  0.0, 0.0,  30, 'ml', ARRAY['espresso','caffè'], true),
('caffe_americano',             'Caffè americano',            'bevande_nonalcoliche','caffe',        3,  0.1,  0.3,  0.0, 0.0, 200, 'ml', ARRAY[]::text[], true),
('decaffeinato',                'Decaffeinato',               'bevande_nonalcoliche','caffe',        2,  0.1,  0.3,  0.0, 0.0,  30, 'ml', ARRAY['deca'], true),
('te_verde',                    'Tè verde',                   'bevande_nonalcoliche','te',           1,  0.0,  0.2,  0.0, 0.0, 250, 'ml', ARRAY['te verde'], true),
('te_nero',                     'Tè nero',                    'bevande_nonalcoliche','te',           1,  0.0,  0.2,  0.0, 0.0, 250, 'ml', ARRAY['te nero'], true),
('tisana_zenzero',              'Tisana zenzero',             'bevande_nonalcoliche','tisane',       1,  0.0,  0.2,  0.0, 0.0, 250, 'ml', ARRAY[]::text[], true),
('tisana_camomilla',            'Tisana camomilla',           'bevande_nonalcoliche','tisane',       1,  0.0,  0.2,  0.0, 0.0, 250, 'ml', ARRAY['camomilla'], true),
('succo_arancia',               'Succo d''arancia',           'bevande_nonalcoliche','succhi',      45,  0.7, 10.4,  0.1, 0.2, 200, 'ml', ARRAY[]::text[], true),
('succo_mela',                  'Succo di mela',              'bevande_nonalcoliche','succhi',      46,  0.1, 11.0,  0.0, 0.2, 200, 'ml', ARRAY[]::text[], true),
('spremuta_arancia',            'Spremuta d''arancia',        'bevande_nonalcoliche','succhi',      38,  0.6,  8.5,  0.1, 0.2, 200, 'ml', ARRAY[]::text[], true),
('spremuta_pompelmo',           'Spremuta di pompelmo',       'bevande_nonalcoliche','succhi',      34,  0.6,  7.6,  0.1, 0.2, 200, 'ml', ARRAY[]::text[], true),
('latte_vegetale_soia',         'Latte di soia',              'bevande_nonalcoliche','latti_vegetali',33, 3.0, 0.4,  1.8, 0.4, 250, 'ml', ARRAY['bevanda soia'], true),
('latte_vegetale_mandorla',     'Latte di mandorla',          'bevande_nonalcoliche','latti_vegetali',22, 0.6, 0.3,  1.1, 0.4, 250, 'ml', ARRAY['bevanda mandorla'], true),
('latte_vegetale_avena',        'Latte di avena',             'bevande_nonalcoliche','latti_vegetali',47, 0.3, 6.7,  1.5, 0.8, 250, 'ml', ARRAY['bevanda avena'], true),
('latte_vegetale_cocco',        'Latte di cocco (bevanda)',   'bevande_nonalcoliche','latti_vegetali',19, 0.2, 2.7,  0.9, 0.2, 250, 'ml', ARRAY[]::text[], true),
('bevanda_proteica_pronta',     'Bevanda proteica pronta',    'bevande_nonalcoliche','sport',       90, 20.0, 1.5,  0.4, 0.0, 250, 'ml', ARRAY['shake proteico'], true),
('integratore_whey_polvere',    'Whey protein polvere',       'bevande_nonalcoliche','sport',      380, 78.0, 6.0,  5.0, 0.0,  30, 'g',  ARRAY['whey','proteine in polvere'], true),

-- ====================== ALCOLICI ======================
('vino_rosso',                  'Vino rosso',                 'alcolici','vino',                    85,  0.1,  2.6,  0.0, 0.0, 125, 'ml', ARRAY[]::text[], true),
('vino_bianco',                 'Vino bianco',                'alcolici','vino',                    82,  0.1,  2.6,  0.0, 0.0, 125, 'ml', ARRAY[]::text[], true),
('vino_rosato',                 'Vino rosato',                'alcolici','vino',                    83,  0.1,  2.5,  0.0, 0.0, 125, 'ml', ARRAY[]::text[], true),
('spumante',                    'Spumante',                   'alcolici','vino',                    80,  0.2,  2.0,  0.0, 0.0, 125, 'ml', ARRAY[]::text[], true),
('prosecco',                    'Prosecco',                   'alcolici','vino',                    85,  0.2,  3.0,  0.0, 0.0, 125, 'ml', ARRAY[]::text[], true),
('birra_chiara',                'Birra chiara',               'alcolici','birra',                   34,  0.5,  3.5,  0.0, 0.0, 330, 'ml', ARRAY['birra'], true),
('birra_doppio_malto',          'Birra doppio malto',         'alcolici','birra',                   70,  0.7,  8.0,  0.0, 0.0, 330, 'ml', ARRAY[]::text[], true),
('birra_artigianale',           'Birra artigianale',          'alcolici','birra',                   50,  0.6,  5.0,  0.0, 0.0, 330, 'ml', ARRAY[]::text[], true),
('cocktail_spritz',             'Spritz',                     'alcolici','cocktail',                95,  0.1,  6.0,  0.0, 0.0, 200, 'ml', ARRAY[]::text[], true),
('cocktail_aperol',             'Aperol cocktail',            'alcolici','cocktail',                95,  0.1,  6.0,  0.0, 0.0, 200, 'ml', ARRAY[]::text[], true),
('gin_tonic',                   'Gin tonic',                  'alcolici','cocktail',               168,  0.0,  9.0,  0.0, 0.0, 200, 'ml', ARRAY[]::text[], true),
('vodka',                       'Vodka',                      'alcolici','distillati',             235,  0.0,  0.0,  0.0, 0.0,  40, 'ml', ARRAY[]::text[], true),
('whisky',                      'Whisky',                     'alcolici','distillati',             250,  0.0,  0.0,  0.0, 0.0,  40, 'ml', ARRAY['whiskey'], true),
('rum',                         'Rum',                        'alcolici','distillati',             231,  0.0,  0.0,  0.0, 0.0,  40, 'ml', ARRAY[]::text[], true),
('amari',                       'Amaro',                      'alcolici','liquori',                215,  0.0, 24.0,  0.0, 0.0,  40, 'ml', ARRAY['amaro'], true),
('limoncello',                  'Limoncello',                 'alcolici','liquori',                232,  0.0, 26.0,  0.0, 0.0,  40, 'ml', ARRAY[]::text[], true)

on conflict (name) do nothing;
